### ISSUE TITLE
Add radiator link

### ISSUE THREAD

**Issue by plato-cambrian** [SocietyPro/playbook#1]
<strike>https://github.com/SocietyPro/playbook/blob/gh-pages/src/markdown/testing.md</strike>
https://github.com/SocietyPro/playbook/blob/gh-pages/src/markdown/devops.md
should have a link to our current build status

**Comment by voodoo-chile** [comment]
I added build status icons as links to the status pages.

**Comment by plato-cambrian** [comment]
Resolved with c0eeb0c06
